#

# Module manifest for module 'PSBabushka'

#

# Generated by: James Ottaway

#

# Generated on: 27/04/2013

#



@{



# Script module or binary module file associated with this manifest.

RootModule = 'PSBabushka.psm1'



# Version number of this module.

ModuleVersion = '0.1'



# ID used to uniquely identify this module

GUID = '6b85d4c1-4176-4a36-a5a7-636f52c6fc7e'



# Author of this module

Author = 'James Ottaway'



# Company or vendor of this module

# CompanyName = ''



# Copyright statement for this module

Copyright = '(c) 2013 James. All rights reserved.'



# Description of the functionality provided by this module

Description = 'A configuration management framework built in PowerShell to help automate Windows environments.'



# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess

NestedModules = @('Functions\Invoke-PSBabushka.psm1', 'Functions\Invoke-PSBabushkaDep.psm1', 'Functions\New-PSBabushkaDep.psm1', 'Functions\Find-PSBabushkaDep.psm1')



# Functions to export from this module

FunctionsToExport = '*'



# HelpInfo URI of this module

HelpInfoURI = 'https://github.com/PSBabushka/PSBabushka'



}

